### ISSUE TITLE
fluent-ffmpeg 2.0 roadmap

### ISSUE THREAD

**Issue by njoyard** [fluent-ffmpeg/node-fluent-ffmpeg#249]
Hi everyone,

The 2.x branch is coming along nicely and I'd like to open this issue to discuss about what we want to do before releasing it.

First of all, I think we should release 2.0 ASAP as it will make maintaining the codebase easier (no need to fix bugs in both branches or adapt PRs).

I did some work lately to enable testing on OSX on travis in addition to Linux; after a few changes [all tests succeed on node 0.8, 0.10 and 0.11 on OSX](https://travis-ci.org/fluent-ffmpeg/node-fluent-ffmpeg/builds/24726248). I was hoping to get a Windows test environment but haven't found a way to do it on travis. Maybe one of you has an idea about a windows-enabled free CI platform ?

In my opinion there are still a few points to address before releasing, but they don't seem blocking to me.
- [x] Rewrite takeScreenshots to have a nicer API and support options better (for now, takeScreenshots generates its own argument list).
- [x] Rewrite mergeToFile to use a single ffmpeg call (and possibly turn it into options methods, eg. `ffmpeg('part1').input('part2').concat().input('part3').concat().save('out')`
- [x] Add methods to enable using '-map' easily with multiple inputs

One mandatory thing to do, I think, is to have a short prerelease period, with a banner added on top of the master README.md explaining that 2.0 is imminent and linking to something that explains how to migrate from 1.x, such as:

> #### Important note about upcoming fluent-ffmpeg version 2.0
> 
> A major 2.0 release is coming soon. This release will feature lots of API cleanup and a cleaner syntax for most methods. Please see the [2.x documentation](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/tree/2.x) for more details.
> 
> It has been designed to be mostly compatible with current fluent-ffmpeg version, but there are some incompatibilities, mainly because deprecated APIs in 1.x have been removed.  See [this paragraph](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/tree/2.x#migrating-from-fluent-ffmpeg-1x) for information on how to migrate.
> 
> A release candidate version will be pushed soon to npm, please take care to update your package.json files if you want to keep using version 1.x:
> 
> ``` js
> {
>   "dependencies": {
>     "fluent-ffmpeg": "~1.7"
>   }
> }
> ```

We also could publish the generated JSDoc in the gh-pages branch to be served at fluent-ffmpeg.github.io.

What are your thoughts about this ? Do you think of anything else that would be mandatory/important/optional for a 2.0 release ?
